language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.4
      env: setup=lowest
    - php: 5.5
    - php: 5.5
      env: setup=lowest
    - php: 5.6
    - php: 5.6
      env: setup=lowest
    - php: 7.0.21
    - php: 7.0.21
      env: setup=lowest
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest
    - php: hhvm
    - php: hhvm
      env: setup=lowest
